### ISSUE TITLE
现在很多单词已经无法查询

### ISSUE THREAD

**Issue by Qitingshe** [bianjp/popup-dict#14]
![image](https://user-images.githubusercontent.com/11593949/53538038-0be84900-3b47-11e9-8b57-ca3003c4148c.png)

**Comment by Alraemon** [comment]
同样的问题，ErrCode也是401，是有道词典禁止使用了接口吗？

**Comment by bianjp** [comment]
有道智云的 API 服务是付费的，内置的账号没钱了，请自行注册一个账号然后配置 app_id, app_secret.

http://ai.youdao.com/doc.s#guide
