### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by CollyKing** [bianjp/popup-dict#2]
使用pip3安装依赖及软件后运行报错:
File "/home/user/.local/lib/python3.5/site-packages/popupdict/query/client/__init__.py", line 8
    valid_clients: List[Type[AbstractQueryClient]] = [
                 ^
SyntaxError: invalid syntax
将默认python版本设为2.7后依然无效.请问是什么问题?

**Comment by bianjp** [comment]
Python 版本号多少？试下升级到 3.6?

**Comment by zbjdonald** [comment]
我用的python 3.5 也是同样的问题

**Comment by bianjp** [comment]
用到了 [PEP 526 -- Syntax for Variable Annotations](https://www.python.org/dev/peps/pep-0526/) 特性，要求版本 3.6+，已修改 README 并发了一个新版本指定 Python >= 3.6。
