### ISSUE TITLE
划词时的问题

### ISSUE THREAD

**Issue by NanerLee** [bianjp/popup-dict#4]
首先感谢作者开发出这么好用的工具！

但是我发现，当我划一个较长的短语或者句子时，程序经常出现只能选到前面的几个单词或者字母

**Comment by bianjp** [comment]
在什么应用中遇到？

不同应用触发剪贴板事件的逻辑不同。有的只在释放鼠标后触发一次，比如浏览器、Gnome Terminal、Evince；有的则会在选中过程中不停触发，每选中一个字符就会触发一次，比如 IDE、编辑器的输入窗口。

为了避免后一种情况下频繁触发查询（HTTP 请求很耗时），我做了一个延时的处理：收到剪贴板事件后，不立即查询，而是记下选中的文本，等待 0.1s 再查询。如果还没到 0.1s 又收到新的剪贴板事件，废弃之前的选中文本，再等待 0.1s。

如果你使用的应用属于后一种情况（可以开启 debug 模式确认一下），划词的速度又比较慢，就会出现还没选中完文本就触发了查询。

0.1s 是我权衡响应速度和误触发频率的一个数值。如果你有需要，也可以修改一下：`popupdict/daemon/query.py` 中的 `QUERY_DELAY` 属性。

**Comment by NanerLee** [comment]
我是在zeal中发现这个的。
看了你的说明，我在chrome和gnome terminal中也试了一下，也会出现这种情况
我发现当文本中出现逗号、句号、下划线或者其他符号时，就很容易出现这个问题，

**Comment by bianjp** [comment]
这大概是选中文本过滤功能造成的。

目前只支持英文字母、空白字符、连字符、单引号，其它都被视为非法字符。监听到选中文本后，会把两端的非法字符全部去掉，如果中间还包括非法字符，就不会触发查询。具体逻辑看 `popupdict/util/selection_filter.py`。

可以开 debug 模式看一下，会输出监听到的选中文本是什么，过滤后是什么。

这个工具主要针对单词和短语，长句不在考虑之内。
